\begin{figure}[htbp] 
\centering 
\subfigure[pic1.]{ 
\begin{minipage}[t]{0.25\linewidth} 
\centering 
\includegraphics[width=1in]{../../results/1.pdf} 
%\caption{fig1} 
\end{minipage}% 
}% 
\subfigure[pic2.]{ 
\begin{minipage}[t]{0.25\linewidth} 
\centering 
\includegraphics[width=1in]{../../results/1.pdf} 
%\caption{fig2} 
\end{minipage}% 
}% 
\subfigure[pic3.]{ 
\begin{minipage}[t]{0.25\linewidth} 
\centering 
\includegraphics[width=1in]{111.eps} 
%\caption{fig2} 
\end{minipage} }% 
\subfigure[pic4.]{ 
\begin{minipage}[t]{0.25\linewidth} 
\centering 
\includegraphics[width=1in]{111.eps} 
%\caption{fig2} 
\end{minipage} 
}% 
\centering 
\caption{ pics} 
\end{figure}
